[versions]
lavalink-api = "4.0.0"
lavalink-server = "4.0.0"

[plugins]
lavalink = { id = "dev.arbjerg.lavalink.gradle-plugin", version = "1.0.10" }

[libraries]
libxmp = { module = "org.helllabs:libxmp-java", version = "1.0.2" }